### ISSUE TITLE
密码不对

### ISSUE THREAD

**Issue by jn3393** [openfans-community-offical/Debian-Pi-Aarch64#4]
按说明输入2边密码，设置密码 进不去系统 也不提示 输入密码回车没反应

**Comment by aiminickwong** [comment]
@jn3393
Please read the manual carefully, the reason is U don not the job as the readme done.

# For no graphic:

## 安全增强
不再设置默认的 root 用户密码，需要用户使用默认pi账户登录后通过"sudo passwd root"命令自行设置root用户密码

- 默认没有开启 root 用户的ssh登录权限（默认仅支持 pi 用户远程ssh登录）

- 不再允许保留初始使用的默认密码，首次使用 pi 账户登录后需要重新设置默认账户pi的密码，具体操作如下：

#### 注意：第一次登录需要重新设置账户密码，这之前需要输入2次默认密码 "raspberry"

登录系统：（输入一次默认密码 “raspberry”）

使用pi账户的默认密码登录系统

接下来系统要求重新设置账户密码 （再次输入一次默认密码 “raspberry”）

然后按照系统提示重新设置pi账户密码并再次输入新密码确认

#### 这里是一个完整的首次登录和修改密码的过程

```shell
raspbian login: pi                ## 默认登录账户  pi
Password:                         ## 默认登录密码  raspberry
You are required to change your password immediately (root enforced)
Changing password for pi.
(current) UNIX password:          ## 系统账户pi的默认密码  raspberry
Enter new UNIX password:          ## 系统账户pi的新密码
Retype new UNIX password:         ## 再次输入系统账户pi的新密码 
```

# For graphic

系统默认没有开启root账户的登录权限

不允许保持使用默认的用户密码

默认系统账户名：pi ，密码：raspberry

首次登录必须修改默认的密码，总共需要输入4次密码：

- 第一次是默认密码 raspberry - PS: 登录认证
- 第二次也是默认密码 raspberry - PS: 修改密码的操作认证
- 第三次设置新密码 - PS: 设置密码
- 第四次确认新密码 - PS: 必须和新设置的密码一致

## 修改密码操作请务必在完成初始安装的3次重启后再进行！

Perhaps I think U problem is ：

**修改密码操作请务必在完成初始安装的3次重启后再进行！**
